### ISSUE TITLE
Test the annotation processors

### ISSUE THREAD

**Issue by elehack** [grouplens/grapht#104]
We need to write automated tests for the annotation processing code.

**Comment by gtrefs** [comment]
I think there is a bug here: [Line 99 of AnnoationValidator](https://github.com/grouplens/grapht/blob/master/src/main/java/org/grouplens/grapht/annotation/AnnotationValidator.java#L99). It should be `Attribute` instead of `Qualifier`. Otherwise, there is no difference in the methods `analyzeQualifiers` and `analyzeAttributes`. Further, there is quite some amount of code duplication here. If you don't mind, I can create a pull request for this.

**Comment by elehack** [comment]
@gtrefs Good catch - that does look like a clear bug. A pull request would be most welcome.

**Comment by gtrefs** [comment]
#110 pull request
