### ISSUE TITLE
Parameterize the exception type on InjectionPointVisitor

### ISSUE THREAD

**Issue by elehack** [grouplens/grapht#111]
The `InjectionPointVisitor` introduced in #109 right now can throw an `InjectionException`. I would like to parameterize it on its exception type, so that the visitor implementation and code that uses it can agree on any checked exception type to throw.

The injection point visitor interface will now look like this:

```java
public interface InjectionPointVisitor<X extends Exception> {
    public void visitField(FieldInjectionPoint ip) throws X;
    /* other methods go here, also throw X */
}
```

The `accept` method will now look like:

```java
public <X extends Exception> void accept(InjectionPointVisitor<X> visitor) throws X;
```

Our `InjectionPointVisitorImpl` will implement `InjectionPointVisitor<ConstructionException>`.

That way different visitors can throw different kinds of exceptions, depending on their use, and those exceptions are properly type-checked.

We can consider introducing a return value type, but we do not yet have a use case.

**Comment by gtrefs** [comment]
Hi Michael,

without knowing the Use Case, I would not parametrize on the exception type. Consider the following: Different methods of the `InjectionPointVisitor` may want to throw different expections. Further, as I read the code right the `InjectionExcpetion` is thrown to indicate an exception during injection. So it is clearly an umbrella exception with a well-defined purpose. I would rather put the exception which causes the injection to fail as cause into an `InjectionException` instance. In this way you can still reason over the cause and maintain a clear API. In code:

```java
throw new InjectionExcpetion("Graph construction not possible",new ConstructionException(fd, e));
```

This leads to less code changes and looks better on the stack trace:
```java
InjectionException: Graph construction not possible
  at ...
Caused by: ConstructionException
  at ...
```

Regards
Gregor

**Comment by elehack** [comment]
@gtrefs Thanks for your input!

Some more context. `ConstructionException` is already a subclass of `InjectionException`, so we wouldn't need to wrap it. But the place where the visitor is currently used is in the instantiation process (`ClassInstantiator`), where only `ConstructionException` can be thrown (because all the other error cases should have already been handled before the code gets to that point). If the visitor interface throws `InjectionException`, then in the instantiator we have to catch `InjectionException`, propagate it if it is really a `ConstructionException`, and wrap it up in a runtime exception (or assertion error) if it is a different subclass of `InjectionException`.

Parameterizing on the exception type allows us to statically declare and check that the instantiator's visitor implementation only throws `ConstructionException`, while leaving the visitor itself open for use in other places in Grapht or in other code (e.g. LensKit's visualization tools, or a future GUI for configuration support).

My thinking is this: the visitor and `accept` methods are means of supporting arbitrary computations over injection points. The types of errors that are appropriate will depend on the computation being performed, and an arbitrary computation entry point should support whatever types of errors those computations wish to signal (which may be something entirely unrelated to the scope of errors covered by `InjectionException`).

Now, that said, I tend to reach for type system encodings pretty fast. Perhaps too fast - I appreciate the push-back. Is there a general pattern to this kind of problem that has been adapted by other systems? My experience with Guava is that they tend to use runtime exceptions everywhere (`Function` and friends) or system-specific interfaces (e.g. the I/O suppliers).

**Comment by gtrefs** [comment]
AFAIK there is a long discussion in the java community whether checked exceptions are a good thing at all. For example, in Java 8 methods which throw a checked exception are not allowed to be used as method references. In general, lamda expressions are not allowed to throw any checked exception. I found an interesting article here:  [Checked exceptions java biggest mistake](http://literatejava.com/exceptions/checked-exceptions-javas-biggest-mistake). From my experience the visitor itself is a tricky pattern (cf. [What design patterns are the worst or most narrowly defined](http://programmers.stackexchange.com/questions/48811/what-design-patterns-are-the-worst-or-most-narrowly-defined)) and I would discourage the idea to make it generic enough for different scenarious because it might break the Single Responsibility principle as it has different reasons for change to meet all those scenarious. Further, if the underlying structure is not pure data-centric it has the tendency to spread closely related logic over several classes. I had a look into `InjectionPointVisitorImpl`. As I see it, parts of the instantiation process are outsourced to it. This makes it hard for me to follow the code. My suggestion is to reconsider whether simple inheritance or the strategy pattern would not be better choices? Sample code:
```java
// Strategy Pattern
// ClassInstantiator.java
final InjectionStrategy injectionStrategy = InjectionStrategies.forInjectionPoint(d.getInjectionPoint());
injectionStrategy.inject(providers.get(d),instance, settersAndArguments)
```
In this way, additonal injection points would only imply a change to the `ClassInstantiator` compared to the whole visitor type hierarchy. However, if you want to stay with the visitor pattern I would suggest the use of `RuntimeException`s because you cannot recover from an exception during injection.

**Comment by elehack** [comment]
@gtrefs The checked exception article is super-helpful, thanks.

I have been migrating towards making more exceptions checked myself, but had not considered how that interacts with functional patterns. And many non-Java JVM languages (Scala, Groovy to name two) completely ignore checked/unchecked.

I think I like the strategy option w/ a 'forInjectionPoint' method; it accomplishes our goal of abstracting the massive set of ifs with `instanceof`, while not introducing the other framework. It does mean that anything switching on the type of the injection point will need to do similar logic, but that is not too large of a sacrifice. It also allows us to keep our exception (for now - might revisit it later), without complex type system encodings.

**Comment by elehack** [comment]
We will implement @gtrefs' proposed design, tracked by ticket #114.
